#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
A neuropsychological test often used to assess attention.

See also:
http://en.wikipedia.org/wiki/Posner_cueing_task

----

WARNING:
This test was generated by pyFlies (https://github.com/igordejanovic/pyFlies)
on 2020-10-25 19:04:59. The code is partially based on the PsychoPy Builder compiler code and demos.

If you are going to regenerate this file from the pyFlies model again
do not edit it manually or else your manual changes will be lost.

If you publish work using this script the most relevant publication is:

Peirce J, Gray JR, Simpson S, MacAskill M, Höchenberger R, Sogo H, Kastman E, Lindeløv JK. (2019)
    PsychoPy2: Experiments in behavior made easy Behav Res 51: 195.
    https://doi.org/10.3758/s13428-018-01193-y

"""
from __future__ import absolute_import, division

import os  # handy system and path functions
import sys  # to get file system encoding
from random import sample

import numpy as np  # whole numpy lib is available, prepend 'np.'
from numpy import (sin, cos, tan, log, log10, pi, average,
                   sqrt, std, deg2rad, rad2deg, linspace, asarray)
from numpy.random import random, randint, normal, shuffle

from psychopy import locale_setup
from psychopy import prefs
from psychopy import gui, visual, sound, core, data, event, logging, clock
from psychopy.constants import (NOT_STARTED, STARTED, PLAYING, PAUSED,
                                STOPPED, FINISHED, PRESSED, RELEASED, FOREVER)
from psychopy.hardware import keyboard


# Ensure that relative paths start from the same directory as this script
_thisDir = os.path.dirname(os.path.abspath(__file__))
os.chdir(_thisDir)

# Store info about the experiment session
psychopyVersion = '2020.1.3'
expName = ''
expInfo = {'participant': '', 'session': '001'}
dlg = gui.DlgFromDict(dictionary=expInfo, sortKeys=False, title=expName)
if dlg.OK == False:
    core.quit()  # user pressed cancel
expInfo['date'] = data.getDateStr()  # add a simple timestamp
expInfo['expName'] = expName
expInfo['psychopyVersion'] = psychopyVersion

# Data file name stem = absolute path + name; later add .psyexp, .csv, .log, etc
filename = os.path.join(_thisDir, u'data',
                        u'%s_%s_%s' % (expInfo['participant'], expName, expInfo['date']))

# An ExperimentHandler isn't essential but helps with data saving
thisExp = data.ExperimentHandler(name=expName, version='',
    extraInfo=expInfo, runtimeInfo=None,
    originPath=__file__,
    savePickle=True, saveWideText=True,
    dataFileName=filename)
# save a log file for detail verbose info
logFile = logging.LogFile(filename+'.log', level=logging.EXP)
logging.console.setLevel(logging.WARNING)  # this outputs to the screen, not a file

endExpNow = False  # flag for 'escape' or other condition => quit the exp
frameTolerance = 0.001  # how close to onset before 'same' frame

# Setup the Window
win = visual.Window(
    size=(1024, 768), fullscr=False,
    color='black', units='height')
# store frame rate of monitor if we can measure it
expInfo['frameRate'] = win.getActualFrameRate()
if expInfo['frameRate'] != None:
    frameDur = 1.0 / round(expInfo['frameRate'])
else:
    frameDur = 1.0 / 60.0  # could not measure, so guess

# create a default keyboard (e.g. to check for escape)
defaultKeyboard = keyboard.Keyboard()

# Initialize components for Posner test
Posner_clock = core.Clock()
Posner_rectangle_0 = visual.Rect(win=win, name='Posner_rectangle_0', pos=(-0.5, 0), size=0.2, lineColor='white', fillColor='black')
Posner_rectangle_0.model_name = None
Posner_rectangle_0.cname = 'Posner_rectangle_0'

Posner_rectangle_1 = visual.Rect(win=win, name='Posner_rectangle_1', pos=(0.5, 0), size=0.2, lineColor='white', fillColor='black')
Posner_rectangle_1.model_name = None
Posner_rectangle_1.cname = 'Posner_rectangle_1'

Posner_cue = visual.Rect(win=win, name='Posner_cue', size=0.18, lineColor='white', fillColor='black')
Posner_cue.model_name = 'cue'
Posner_cue.cname = 'Posner_cue'

Posner_target = visual.Rect(win=win, name='Posner_target', size=0.2, lineColor='white', fillColor='white')
Posner_target.model_name = 'target'
Posner_target.cname = 'Posner_target'

Posner_keyboard_4 = keyboard.Keyboard()
Posner_keyboard_4.model_name = None
Posner_keyboard_4.cname = 'Posner_keyboard_4'
Posner_keyboard_4.valid_keys = ['left', 'right', 'quit']

Posner_circle_5 = visual.Circle(win=win, name='Posner_circle_5', fillColor='green', lineColor='green', radius=1.0, pos=(0.0, 0.0), size=0.2)
Posner_circle_5.model_name = None
Posner_circle_5.cname = 'Posner_circle_5'

Posner_circle_6 = visual.Circle(win=win, name='Posner_circle_6', fillColor='red', lineColor='green', radius=1.0, pos=(0.0, 0.0), size=0.2)
Posner_circle_6.model_name = None
Posner_circle_6.cname = 'Posner_circle_6'


Posner_components = [
    Posner_rectangle_0,
    Posner_rectangle_1,
    Posner_cue,
    Posner_target,
    Posner_keyboard_4,
    Posner_circle_5,
    Posner_circle_6]

# Initialize components for Practice screen
Practice_clock = core.Clock()
Practice = visual.TextStim(win=win, name='Practice', height=0.05,
    text=r'''Posner Cueing
    -------------

    You will be presented with the two empty boxes positioned left and right from
    the center of the screen. You should concentrate on the center of the screen
    and wait for the cue. The cue will be presented as a box highlight. After some
    time a cross shaped object will be presented in some of the squares. React as
    fast as you can by pressing space button when you detect a cross shaped
    object.

    Press SPACE for practice block.
''')

# Initialize components for Real screen
Real_clock = core.Clock()
Real = visual.TextStim(win=win, name='Real', height=0.05,
    text=r'''Posner Cueing
    -------------

    Now a REAL testing will be performed.

    Press SPACE to start the test.
''')



# Trial component settings for Posner test
Posner_2 = [
       # Trial 1
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.25,
                'duration': 1.045,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.295,
                'duration': 0.0,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.295,
                'duration': 0.0,
                'params': {'correct': 'right'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
       # Trial 2
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.113,
                'duration': 1.317,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.43,
                'duration': 0.0,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.43,
                'duration': 0.0,
                'params': {'correct': 'left'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
       # Trial 3
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.203,
                'duration': 1.049,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.252,
                'duration': 0.0,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.252,
                'duration': 0.0,
                'params': {'correct': 'left'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
       # Trial 4
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.258,
                'duration': 1.093,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.351,
                'duration': 0.0,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.351,
                'duration': 0.0,
                'params': {'correct': 'right'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
       # Trial 5
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.463,
                'duration': 1.178,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.641,
                'duration': 0.0,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.641,
                'duration': 0.0,
                'params': {'correct': 'left'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
       # Trial 6
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.477,
                'duration': 1.237,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.714,
                'duration': 0.0,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.714,
                'duration': 0.0,
                'params': {'correct': 'right'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
       # Trial 7
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.173,
                'duration': 1.417,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.59,
                'duration': 0.0,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.59,
                'duration': 0.0,
                'params': {'correct': 'left'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
       # Trial 8
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.243,
                'duration': 1.164,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.407,
                'duration': 0.0,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.407,
                'duration': 0.0,
                'params': {'correct': 'right'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
]


# Trial component settings for Posner test
Posner_4 = [
       # Trial 1
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.398,
                'duration': 1.199,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.597,
                'duration': 0.0,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.597,
                'duration': 0.0,
                'params': {'correct': 'right'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
       # Trial 2
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.145,
                'duration': 1.174,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.319,
                'duration': 0.0,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.319,
                'duration': 0.0,
                'params': {'correct': 'left'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
       # Trial 3
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.434,
                'duration': 1.034,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.468,
                'duration': 0.0,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.468,
                'duration': 0.0,
                'params': {'correct': 'left'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
       # Trial 4
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.217,
                'duration': 1.029,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.246,
                'duration': 0.0,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.246,
                'duration': 0.0,
                'params': {'correct': 'right'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
       # Trial 5
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.283,
                'duration': 1.333,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.616,
                'duration': 0.0,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.616,
                'duration': 0.0,
                'params': {'correct': 'left'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
       # Trial 6
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.286,
                'duration': 1.414,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.7,
                'duration': 0.0,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.7,
                'duration': 0.0,
                'params': {'correct': 'right'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
       # Trial 7
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.082,
                'duration': 1.198,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.28,
                'duration': 0.0,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.28,
                'duration': 0.0,
                'params': {'correct': 'left'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
       # Trial 8
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.214,
                'duration': 1.141,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.355,
                'duration': 0.0,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.355,
                'duration': 0.0,
                'params': {'correct': 'right'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
]

# Trial component settings for Posner test
Posner_5 = [
       # Trial 1
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.471,
                'duration': 1.008,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.479,
                'duration': 0.0,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.479,
                'duration': 0.0,
                'params': {'correct': 'right'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
       # Trial 2
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.02,
                'duration': 1.022,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.042,
                'duration': 0.0,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.042,
                'duration': 0.0,
                'params': {'correct': 'left'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
       # Trial 3
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.19,
                'duration': 1.139,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.329,
                'duration': 0.0,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.329,
                'duration': 0.0,
                'params': {'correct': 'left'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
       # Trial 4
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.021,
                'duration': 1.387,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.408,
                'duration': 0.0,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.408,
                'duration': 0.0,
                'params': {'correct': 'right'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
       # Trial 5
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.162,
                'duration': 1.412,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.574,
                'duration': 0.0,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.574,
                'duration': 0.0,
                'params': {'correct': 'left'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
       # Trial 6
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.062,
                'duration': 1.033,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.095,
                'duration': 0.0,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.095,
                'duration': 0.0,
                'params': {'correct': 'right'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
       # Trial 7
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.36,
                'duration': 1.157,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.517,
                'duration': 0.0,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.517,
                'duration': 0.0,
                'params': {'correct': 'left'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
       # Trial 8
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.378,
                'duration': 1.442,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.82,
                'duration': 0.0,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.82,
                'duration': 0.0,
                'params': {'correct': 'right'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
]

# Trial component settings for Posner test
Posner_6 = [
       # Trial 1
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.319,
                'duration': 1.409,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.728,
                'duration': 0.0,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.728,
                'duration': 0.0,
                'params': {'correct': 'right'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
       # Trial 2
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.3,
                'duration': 1.471,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.771,
                'duration': 0.0,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.771,
                'duration': 0.0,
                'params': {'correct': 'left'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
       # Trial 3
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.154,
                'duration': 1.37,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.524,
                'duration': 0.0,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.524,
                'duration': 0.0,
                'params': {'correct': 'left'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
       # Trial 4
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.391,
                'duration': 1.378,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.769,
                'duration': 0.0,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.769,
                'duration': 0.0,
                'params': {'correct': 'right'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
       # Trial 5
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.102,
                'duration': 1.472,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.574,
                'duration': 0.0,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.574,
                'duration': 0.0,
                'params': {'correct': 'left'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
       # Trial 6
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.129,
                'duration': 1.141,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.27,
                'duration': 0.0,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.27,
                'duration': 0.0,
                'params': {'correct': 'right'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
       # Trial 7
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.334,
                'duration': 1.204,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.538,
                'duration': 0.0,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.538,
                'duration': 0.0,
                'params': {'correct': 'left'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
       # Trial 8
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.333,
                'duration': 1.044,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.377,
                'duration': 0.0,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.377,
                'duration': 0.0,
                'params': {'correct': 'right'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
]

# Trial component settings for Posner test
Posner_7 = [
       # Trial 1
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.446,
                'duration': 1.207,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.653,
                'duration': 0.0,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.653,
                'duration': 0.0,
                'params': {'correct': 'right'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
       # Trial 2
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.255,
                'duration': 1.208,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.463,
                'duration': 0.0,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.463,
                'duration': 0.0,
                'params': {'correct': 'left'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
       # Trial 3
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.083,
                'duration': 1.03,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.113,
                'duration': 0.0,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.113,
                'duration': 0.0,
                'params': {'correct': 'left'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
       # Trial 4
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.455,
                'duration': 1.278,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.733,
                'duration': 0.0,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.733,
                'duration': 0.0,
                'params': {'correct': 'right'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
       # Trial 5
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.459,
                'duration': 1.41,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.869,
                'duration': 0.0,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.869,
                'duration': 0.0,
                'params': {'correct': 'left'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
       # Trial 6
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.357,
                'duration': 1.272,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.629,
                'duration': 0.0,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.629,
                'duration': 0.0,
                'params': {'correct': 'right'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
       # Trial 7
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.468,
                'duration': 1.235,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.703,
                'duration': 0.0,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.703,
                'duration': 0.0,
                'params': {'correct': 'left'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
       # Trial 8
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.065,
                'duration': 1.289,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.354,
                'duration': 0.0,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.354,
                'duration': 0.0,
                'params': {'correct': 'right'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
]

# Trial component settings for Posner test
Posner_8 = [
       # Trial 1
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.268,
                'duration': 1.238,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.506,
                'duration': 0.0,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.506,
                'duration': 0.0,
                'params': {'correct': 'right'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
       # Trial 2
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.41,
                'duration': 1.334,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.744,
                'duration': 0.0,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.744,
                'duration': 0.0,
                'params': {'correct': 'left'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
       # Trial 3
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.443,
                'duration': 1.077,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.52,
                'duration': 0.0,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.52,
                'duration': 0.0,
                'params': {'correct': 'left'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
       # Trial 4
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.48,
                'duration': 1.145,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.625,
                'duration': 0.0,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.625,
                'duration': 0.0,
                'params': {'correct': 'right'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
       # Trial 5
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.221,
                'duration': 1.456,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.677,
                'duration': 0.0,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.677,
                'duration': 0.0,
                'params': {'correct': 'left'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
       # Trial 6
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.418,
                'duration': 1.472,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.89,
                'duration': 0.0,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.89,
                'duration': 0.0,
                'params': {'correct': 'right'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
       # Trial 7
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.052,
                'duration': 1.399,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.451,
                'duration': 0.0,
                'params': {'pos': (-0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.451,
                'duration': 0.0,
                'params': {'correct': 'left'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
       # Trial 8
      {'ph_exec': [
            {'inst': Posner_rectangle_0,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_rectangle_1,
                'type': 'visual.rectangle',
                'at': 0.0,
                'duration': 0.0,
                'params': {}},
            {'inst': Posner_cue,
                'type': 'visual.rectangle',
                'at': 1.019,
                'duration': 1.174,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_target,
                'type': 'visual.rectangle',
                'at': 2.193,
                'duration': 0.0,
                'params': {'pos': (0.5, 0)}},
            {'inst': Posner_keyboard_4,
                'type': 'input.keyboard',
                'at': 2.193,
                'duration': 0.0,
                'params': {'correct': 'right'}}],
        'ph_error': [
            {'inst': Posner_circle_6,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}],
        'ph_correct': [
            {'inst': Posner_circle_5,
                'type': 'visual.circle',
                'at': 0.0,
                'duration': 0.3,
                'params': {}}]},
]



def get_param(comp, param_name):
    """
    Returns component param for the given name
    """
    try:
        return [v for k, v in comp['params'].items() if k == param_name][0]
    except KeyError:
        return None


def execute_screen(screen, duration):
    "Displays the given screen"
    screen.setAutoDraw(True)
    win.flip()

    # Wait for the duration. During wait check for key presses.
    key = event.waitKeys(maxWait=duration if duration > 0 else float('inf'))
    screen.setAutoDraw(False)

    if key in ['escape', 'q']:
        core.quit()


def execute_test(test_trials, test_components, random=False, practice=False):
    """
    Execute given test.  Run components with the given timing and collect
    responses.
    """

    def execute_phase(components, should_record=False):
        if not components:
            return
        # reset timers
        t = 0
        _timeToFirstFrame = win.getFutureFlipTime(clock="now")
        trialClock.reset(-_timeToFirstFrame)  # t0 is time of first possible flip
        frameN = -1
        continueTest = True
        correct_response = True

        while continueTest:
            t = trialClock.getTime()
            tThisFlip = win.getFutureFlipTime(clock=trialClock)
            tThisFlipGlobal = win.getFutureFlipTime(clock=None)
            frameN = frameN + 1  # number of completed frames (so 0 is the first frame)

            # update/draw components on each frame
            for component in components:
                cinst = component['inst']
                ctype = component['type']

                if cinst.status == NOT_STARTED \
                    and tThisFlip >= component['at'] - frameTolerance:
                    # keep track of start time/frame for later
                    cinst.frameNStart = frameN  # exact frame index
                    cinst.tStart = t  # local t and not account for scr refresh
                    cinst.tStartRefresh = tThisFlipGlobal  # on global time
                    win.timeOnFlip(cinst, 'tStartRefresh')  # time at next scr refresh
                    cinst.status = STARTED

                    # Set component parameters for this trial
                    for pname, pval in component['params'].items():
                        setattr(cinst, pname, pval)

                    # If component is audible start playing
                    if 'audible' in ctype:
                        cinst.play()
                    elif 'mouse' in ctype:
                        cinst.mouseClock.reset()
                        # if button is down already this ISN'T a new click
                        prevButtonState = cinst.getPressed()
                    elif 'keyboard' in ctype:
                        cinst.getKeys()
                        cinst.clock.reset()
                        cinst.start()

                    # Display component on the next flip
                    if 'visual' in ctype:
                        cinst.setAutoDraw(True)

                if 'keyboard' in ctype and cinst.status == STARTED:
                    keys = cinst.getKeys(cinst.valid_keys, waitRelease=False)
                    if 'quit' in keys:
                        core.quit()
                    if keys:
                        correct_keys = get_param(component, 'correct')
                        correct_response = not correct_keys or keys[0].name in correct_keys
                        cinst.key_name = keys[0].name
                        cinst.key_rt = keys[0].rt
                        cinst.key_correct = correct_response
                        continueTest = False

                elif 'mouse' in ctype and cinst.status == STARTED:
                    buttons = cinst.getPressed()
                    if buttons != prevButtonState:  # button state changed?
                        prevButtonState = buttons
                        if sum(buttons) > 0:  # state changed to a new click
                            # If target object(s) are/is defined
                            # check if the mouse was inside our 'clickable' objects
                            # If we don't have targets, then any click is valid
                            x, y = cinst.getPos()
                            gotValidClick = not bool(cinst.targets)
                            for obj in cinst.targets:
                                if obj.contains(x, y):
                                    gotValidClick = True
                                    cinst.clicked_name.append(obj.name)
                            cinst.x.append(x)
                            cinst.y.append(y)
                            buttons = cinst.getPressed()
                            cinst.leftButton.append(buttons[0])
                            cinst.midButton.append(buttons[1])
                            cinst.rightButton.append(buttons[2])
                            cinst.time.append(cinst.mouseClock.getTime())
                            if gotValidClick:  # abort routine on response
                                continueTest = False

                if component['duration'] > 0 and cinst.status == STARTED:
                    # is it time to stop? (based on global clock, using actual start)
                    if tThisFlipGlobal > cinst.tStartRefresh \
                        + component['duration'] - frameTolerance:
                        # keep track of stop time/frame for later
                        cinst.tStop = t  # not accounting for scr refresh
                        cinst.frameNStop = frameN  # exact frame index
                        cinst.status = FINISHED
                        win.timeOnFlip(cinst, 'tStopRefresh')  # time at next scr refresh

                        # If component is audible stop playing
                        if 'audible' in ctype:
                            cinst.stop()
                        elif 'visual' in ctype:
                            cinst.setAutoDraw(False)

            # check for quit (typically the Esc key)
            if endExpNow or defaultKeyboard.getKeys(keyList=["escape"]):
                core.quit()

            # check if all components have finished
            if not continueTest:
                break
            # will revert to True if at least one component still running
            continueTest = False
            for thisComponent in [c['inst'] for c in components]:
                if hasattr(thisComponent, "status") and thisComponent.status != FINISHED:
                    continueTest = True
                    # at least one component has not yet finished
                    break

            # refresh the screen
            # don't flip if this test is over or we'll get a blank screen
            if continueTest:
                win.flip()

        # At the end of the phase stop all components
        for component in components:
            cinst = component['inst']
            ctype = component['type']
            if 'visual' in ctype:
                cinst.setAutoDraw(False)
            # If component is audible stop playing
            elif 'audible' in ctype:
                cinst.stop()

        # Register interesting data
        for component in components:
            cinst = component['inst']
            ctype = component['type']

            def datap(attr, name=None):
                name = attr if name is None else name
                cname = cinst.model_name if cinst.model_name else cinst.cname
                col_name = '{}.{}'.format(cname, name)
                value = getattr(cinst, attr)
                if type(value) is list:
                    value = value[0]
                return (col_name, value)

            # component parameters for this trial
            for pname, pval in component['params'].items():
                cname = cinst.model_name if cinst.model_name else cinst.cname
                thisExp.addData('{}.{}'.format(cname, pname), pval)

            if 'keyboard' in ctype:
                thisExp.addData(*datap('key_name', 'name'))
                thisExp.addData(*datap('key_rt', 'rt'))
                thisExp.addData(*datap('key_correct', 'correct'))
            elif 'mouse' in ctype:
                for dname in ['x', 'y', 'leftButton', 'midButton',
                              'rightButton', 'time', 'clicked_name']:
                    thisExp.addData(*datap(dname))
                thisExp.addData(*datap('tStart', 'started'))
                thisExp.addData(*datap('tStopped', 'stopped'))

            elif cinst.model_name is not None:
                # If we defined name for component in the model we shall record
                # its start/stop times/frames
                thisExp.addData(*datap('tStartRefresh', 'started'))
                thisExp.addData(*datap('frameNStart', 'startFrame'))
                thisExp.addData(*datap('tStopRefresh', 'stopped'))
                thisExp.addData(*datap('frameNStop', 'stopFrame'))

        thisExp.nextEntry()

        return correct_response

    # Run trials
    phases = ['ph_fix', 'ph_exec', 'ph_correct', 'ph_error']
    for trial in sample(test_trials, len(test_trials)) if random else test_trials:
        # Initialize components for this trial
        for component in [c for phase in phases for c in trial.get(phase, [])]:
            cinst = component['inst']
            cparams = component['params']
            ctype = component['type']
            cinst.tStart = None
            cinst.tStop = None
            cinst.tStartRefresh = None
            cinst.tStopRefresh = None
            cinst.frameNStart = None
            cinst.frameNStop = None
            if hasattr(cinst, 'status'):
                cinst.status = NOT_STARTED

            # Set component parameters for this trial
            for pname, pval in cparams.items():
                setattr(cinst, pname, pval)

            # If component is audible set duration
            if 'audible' in ctype:
                cinst.secs = component['duration']
            elif 'mouse' in ctype:
                cinst.x = []
                cinst.y = []
                cinst.leftButton = []
                cinst.midButton = []
                cinst.rightButton = []
                cinst.time = []
                cinst.clicked_name = []

        for phase in ['ph_fix', 'ph_exec']:
            if phase in trial:
                correct = execute_phase(trial[phase], should_record=phase=='ph_exec')

        if correct and 'ph_correct' in trial:
            execute_phase(trial['ph_correct'])
        elif 'ph_error' in trial:
            execute_phase(trial['ph_error'])

# Create some handy timers
globalClock = core.Clock()  # to track the time since experiment started
trialClock = core.Clock()
routineTimer = core.CountdownTimer()  # to track time remaining of each (non-slip) routine

# Experiment flow
execute_screen(Practice, 0.0)
execute_test(Posner_2, Posner_components, random=True, practice=True)
execute_screen(Real, 0.0)
execute_test(Posner_4, Posner_components, random=True)
execute_test(Posner_5, Posner_components, random=True)
execute_test(Posner_6, Posner_components, random=True)
execute_test(Posner_7, Posner_components, random=True)
execute_test(Posner_8, Posner_components, random=True)

# Flip one final time so any remaining win.callOnFlip()
# and win.timeOnFlip() tasks get executed before quitting
win.flip()

# these shouldn't be strictly necessary (should auto-save)
thisExp.saveAsWideText(filename+'.csv', delim='auto')
thisExp.saveAsPickle(filename)
logging.flush()
# make sure everything is closed down
thisExp.abort()  # or data files will save again on exit
win.close()
core.quit()